# Generated by Django 3.2.16 on 2025-05-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('busines', 'Бизнес'), ('personal', 'Личное'), ('tax', 'Налог')], max_length=20)),
                ('type', models.CharField(choices=[('replenishment', 'Пополнение'), ('debiting', 'Списание')], max_length=20)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Comment', models.TextField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.category')),
            ],
        ),
    ]
