# Generated by Django 5.2 on 2025-05-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_status_type'),
        ('records', '0002_record_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.status'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.type'),
        ),
    ]
