# Generated by Django 5.2 on 2025-05-02 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_rename_types_category_type'),
        ('records', '0003_alter_record_status_alter_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Comment',
            field=models.TextField(max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='guides.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='record',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='record',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.type', verbose_name='Тип'),
        ),
    ]
