# Generated by Django 5.2 on 2025-05-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_comment_alter_record_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
    ]
