# Generated by Django 5.2 on 2025-05-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_rename_types_category_type'),
        ('records', '0005_alter_record_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guides.status', verbose_name='Статус'),
        ),
    ]
