# Generated by Django 3.2.16 on 2025-05-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='Subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guides.category'),
        ),
    ]
