# Generated by Django 5.2 on 2025-05-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20250501_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='Subcategory',
            new_name='category',
        ),
    ]
