# Generated by Django 5.2 on 2025-05-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0007_category_types_alter_category_name_alter_status_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='types',
            new_name='type',
        ),
    ]
